version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: db-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gym
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"